In [23]:
from pathlib import Path
import pandas as pd
import numpy as np
import re
import pyarrow

In [24]:
RAW_PATH = Path("../data/raw")

dfs = {}

for file in RAW_PATH.glob("*.csv"):
    dfs[file.stem] = pd.read_csv(file)

In [25]:
for name, df in dfs.items():
    print("=" * 70)
    print(name.upper())
    print("=" * 70)

    print(df.info())

    print("\nMissing values")
    print(df.isna().sum())

    print("\nDuplicate rows:", df.duplicated().sum())

    print("\nFirst rows")
    display(df.head())

======================================================================
CIRCUITS
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   circuitId   78 non-null     int64
 1   circuitRef  78 non-null     object
 2   name        78 non-null     object
 3   location    78 non-null     object
 4   country     78 non-null     object
 5   lat         78 non-null     float64
 6   lng         78 non-null     float64
 7   alt         78 non-null     int64
 8   url         78 non-null     object
dtypes: float64(2), int64(2), object(5)
memory usage: 5.6+ KB
None

Missing values
circuitId     0
circuitRef    0
name          0
location      0
country       0
lat           0
lng           0
alt           0
url           0
dtype: int64

Duplicate rows: 0

First rows

,circuitId,circuitRef,name,location,country,lat,lng,alt,url
0,1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.84970,144.96800,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
1,2,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.73800,18,http://en.wikipedia.org/wiki/Sepang_Internatio...
2,3,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.03250,50.51060,7,http://en.wikipedia.org/wiki/Bahrain_Internati...
3,4,catalunya,Circuit de Barcelona-Catalunya,Montmeló,Spain,41.57000,2.26111,109,http://en.wikipedia.org/wiki/Circuit_de_Barcel...
4,5,istanbul,Istanbul Park,Istanbul,Turkey,40.95170,29.40500,130,http://en.wikipedia.org/wiki/Istanbul_Park

======================================================================
CONSTRUCTORS
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   constructorId   214 non-null    int64
 1   constructorRef  214 non-null    object
 2   name            214 non-null    object
 3   nationality     214 non-null    object
 4   url             214 non-null    object
dtypes: int64(1), object(4)
memory usage: 8.5+ KB
None

Missing values
constructorId     0
constructorRef    0
name              0
nationality       0
url               0
dtype: int64

Duplicate rows: 0

First rows

,constructorId,constructorRef,name,nationality,url
0,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
1,2,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso

======================================================================
CONSTRUCTOR_RESULTS
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12953 entries, 0 to 12952
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   constructorResultsId  12953 non-null  int64
 1   raceId                12953 non-null  int64
 2   constructorId         12953 non-null  int64
 3   points                12953 non-null  float64
 4   status                12953 non-null  object
dtypes: float64(1), int64(3), object(1)
memory usage: 506.1+ KB
None

Missing values
constructorResultsId    0
raceId                  0
constructorId           0
points                  0
status                  0
dtype: int64

Duplicate rows: 0

First rows

   constructorResultsId  raceId  constructorId  points status
0                     1      18              1    14.0     \N
1                     2      18              2     8.0     \N
2                     3      18              3     9.0     \N
3                     4      18              4     5.0     \N
4                     5      18              5     2.0     \N

======================================================================
CONSTRUCTOR_STANDINGS
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13719 entries, 0 to 13718
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   constructorStandingsId  13719 non-null  int64
 1   raceId                  13719 non-null  int64
 2   constructorId           13719 non-null  int64
 3   points                  13719 non-null  float64
 4   position                13719 non-null  object
 5   positionText            13719 non-null  object
 6   wins                    13719 non-null  int64
dtypes: float64(1), int64(4), object(2)
memory usage: 750.4+ KB
None

Missing values
constructorStandingsId    0
raceId                    0
constructorId             0
points                    0
position                  0
positionText              0
wins                      0
dtype: int64

Duplicate rows: 0

First rows

,constructorStandingsId,raceId,constructorId,points,position,positionText,wins
0,1,18,1,14.0,1,1,1
1,2,18,2,8.0,3,3,0
2,3,18,3,9.0,2,2,0
3,4,18,4,5.0,4,4,0
4,5,18,5,2.0,5,5,0

======================================================================
DRIVERS
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 865 entries, 0 to 864
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   driverId     865 non-null    int64
 1   driverRef    865 non-null    object
 2   number       865 non-null    object
 3   code         865 non-null    object
 4   forename     865 non-null    object
 5   surname      865 non-null    object
 6   dob          865 non-null    object
 7   nationality  865 non-null    object
 8   url          865 non-null    object
dtypes: int64(1), object(8)
memory usage: 60.9+ KB
None

Missing values
driverId       0
driverRef      0
number         0
code           0
forename       0
surname        0
dob            0
nationality    0
url            0
dtype: int64

Duplicate rows: 0

First rows

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen

======================================================================
DRIVER_STANDINGS
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35537 entries, 0 to 35536
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   driverStandingsId  35537 non-null  int64
 1   raceId             35537 non-null  int64
 2   driverId           35537 non-null  int64
 3   points             35537 non-null  float64
 4   position           35537 non-null  object
 5   positionText       35537 non-null  object
 6   wins               35537 non-null  int64
dtypes: float64(1), int64(4), object(2)
memory usage: 1.9+ MB
None

Missing values
driverStandingsId    0
raceId               0
driverId             0
points               0
position             0
positionText         0
wins                 0
dtype: int64

Duplicate rows: 0

First rows

   driverStandingsId  raceId  driverId  points position positionText  wins
0                  1      18         1    10.0        1            1     1
1                  2      18         2     8.0        2            2     0
2                  3      18         3     6.0        3            3     0
3                  4      18         4     5.0        4            4     0
4                  5      18         5     4.0        5            5     0

======================================================================
LAP_TIMES
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 875093 entries, 0 to 875092
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   raceId        875093 non-null  int64
 1   driverId      875093 non-null  int64
 2   lap           875093 non-null  int64
 3   position      875093 non-null  int64
 4   time          875093 non-null  object
 5   milliseconds  875093 non-null  int64
dtypes: int64(5), object(1)
memory usage: 40.1+ MB
None

Missing values
raceId          0
driverId        0
lap             0
position        0
time            0
milliseconds    0
dtype: int64

Duplicate rows: 1707

First rows

   raceId  driverId  lap  position      time  milliseconds
0     479       137    1         1  1:42.085        102085
1     479       137    2         2  1:36.287         96287
2     479       137    3         2  1:34.627         94627
3     479       137    4         2  1:34.041         94041
4     479       137    5         2  1:33.699         93699

======================================================================
PIT_STOPS
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22424 entries, 0 to 22423
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   raceId        22424 non-null  int64
 1   driverId      22424 non-null  int64
 2   stop          22424 non-null  int64
 3   lap           22424 non-null  int64
 4   time          22424 non-null  object
 5   duration      22424 non-null  object
 6   milliseconds  22424 non-null  object
dtypes: int64(4), object(3)
memory usage: 1.2+ MB
None

Missing values
raceId          0
driverId        0
stop            0
lap             0
time            0
duration        0
milliseconds    0
dtype: int64

Duplicate rows: 0

First rows

   raceId  driverId  stop  lap      time duration milliseconds
0     258       100     1    1  14:01:34   49.111        49111
1     258        79     1   17  14:20:46   28.482        28482
2     258        57     1   18  14:22:35   43.745        43745
3     258        71     1   18  14:23:00   21.992        21992
4     258       105     1   19  14:24:39   27.693        27693

======================================================================
QUALIFYING
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11146 entries, 0 to 11145
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   qualifyId      11146 non-null  int64
 1   raceId         11146 non-null  int64
 2   driverId       11146 non-null  int64
 3   constructorId  11146 non-null  int64
 4   number         11146 non-null  int64
 5   position       11146 non-null  int64
 6   q1             11146 non-null  object
 7   q2             11146 non-null  object
 8   q3             11146 non-null  object
dtypes: int64(6), object(3)
memory usage: 783.8+ KB
None

Missing values
qualifyId        0
raceId           0
driverId         0
constructorId    0
number           0
position         0
q1               0
q2               0
q3               0
dtype: int64

Duplicate rows: 0

First rows

,qualifyId,raceId,driverId,constructorId,number,position,q1,q2,q3
0,1,18,1,1,22,1,1:26.572,1:25.187,1:26.714
1,2,18,9,2,4,2,1:26.103,1:25.315,1:26.869
2,3,18,5,1,23,3,1:25.664,1:25.452,1:27.079
3,4,18,13,6,2,4,1:25.994,1:25.691,1:27.178
4,5,18,2,2,3,5,1:25.960,1:25.518,1:27.236

======================================================================
RACES
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1171 entries, 0 to 1170
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   raceId       1171 non-null   int64
 1   year         1171 non-null   int64
 2   round        1171 non-null   int64
 3   circuitId    1171 non-null   int64
 4   name         1171 non-null   object
 5   date         1171 non-null   object
 6   time         1171 non-null   object
 7   url          1171 non-null   object
 8   fp1_date     1171 non-null   object
 9   fp1_time     1171 non-null   object
 10  fp2_date     1171 non-null   object
 11  fp2_time     1171 non-null   object
 12  fp3_date     1171 non-null   object
 13  fp3_time     1171 non-null   object
 14  quali_date   1171 non-null   object
 15  quali_time   1171 non-null   object
 16  sprint_date  1171 non-null   object
 17  sprint_time  1171 non-null   object
dtypes: int64(4), object(14)
memory usage: 164.8+ KB
None

Missing values
raceId         0
year           0
round          0
circuitId      0
name           0
date           0
time           0
url            0
fp1_date       0
fp1_time       0
fp2_date       0
fp2_time       0
fp3_date       0
fp3_time       0
quali_date     0
quali_time     0
sprint_date    0
sprint_time    0
dtype: int64

Duplicate rows: 0

First rows

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N

======================================================================
RESULTS
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27414 entries, 0 to 27413
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   resultId         27414 non-null  int64
 1   raceId           27414 non-null  int64
 2   driverId         27414 non-null  int64
 3   constructorId    27414 non-null  int64
 4   number           27414 non-null  object
 5   grid             27414 non-null  object
 6   position         27414 non-null  object
 7   positionText     27414 non-null  object
 8   positionOrder    27414 non-null  int64
 9   points           27414 non-null  float64
 10  laps             27414 non-null  int64
 11  time             27414 non-null  object
 12  milliseconds     27414 non-null  object
 13  fastestLap       27414 non-null  object
 14  rank             27414 non-null  object
 15  fastestLapTime   27414 non-null  object
 16  fastestLapSpeed  27414 non-null  object
 17  statusId         27414 non-null  int64
dtypes: float64(1), int64(7), object(10)
memory usage: 3.8+ MB
None

Missing values
resultId           0
raceId             0
driverId           0
constructorId      0
number             0
grid               0
position           0
positionText       0
positionOrder      0
points             0
laps               0
time               0
milliseconds       0
fastestLap         0
rank               0
fastestLapTime     0
fastestLapSpeed    0
statusId           0
dtype: int64

Duplicate rows: 0

First rows

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.3,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1

======================================================================
SEASONS
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   year    77 non-null     int64
 1   url     77 non-null     object
dtypes: int64(1), object(1)
memory usage: 1.3+ KB
None

Missing values
year    0
url     0
dtype: int64

Duplicate rows: 0

First rows

   year                                                url
0  2009  http://en.wikipedia.org/wiki/2009_Formula_One_...
1  2008  http://en.wikipedia.org/wiki/2008_Formula_One_...
2  2007  http://en.wikipedia.org/wiki/2007_Formula_One_...
3  2006  http://en.wikipedia.org/wiki/2006_Formula_One_...
4  2005  http://en.wikipedia.org/wiki/2005_Formula_One_...

======================================================================
SPRINT_RESULTS
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 546 entries, 0 to 545
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   resultId        546 non-null    int64
 1   raceId          546 non-null    int64
 2   driverId        546 non-null    int64
 3   constructorId   546 non-null    int64
 4   number          546 non-null    int64
 5   grid            546 non-null    int64
 6   position        546 non-null    object
 7   positionText    546 non-null    object
 8   positionOrder   546 non-null    int64
 9   points          546 non-null    int64
 10  laps            546 non-null    int64
 11  time            546 non-null    object
 12  milliseconds    546 non-null    object
 13  fastestLap      546 non-null    object
 14  fastestLapTime  546 non-null    object
 15  statusId        546 non-null    object
 16  rank            546 non-null    object
dtypes: int64(9), object(8)
memory usage: 72.6+ KB
None

Missing values
resultId          0
raceId            0
driverId          0
constructorId     0
number            0
grid              0
position          0
positionText      0
positionOrder     0
points            0
laps              0
time              0
milliseconds      0
fastestLap        0
fastestLapTime    0
statusId          0
rank              0
dtype: int64

Duplicate rows: 0

First rows

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,fastestLapTime,statusId,rank
0,1,1061,830,9,33,2,1,1,1,3,17,25:38.426,1538426,14,1:30.013,1,\N
1,2,1061,1,131,44,1,2,2,2,2,17,+1.430,1539856,17,1:29.937,1,\N
2,3,1061,822,131,77,3,3,3,3,1,17,+7.502,1545928,17,1:29.958,1,\N
3,4,1061,844,6,16,4,4,4,4,0,17,+11.278,1549704,16,1:30.163,1,\N
4,5,1061,846,1,4,6,5,5,5,0,17,+24.111,1562537,16,1:30.566,1,\N

======================================================================
STATUS
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140 entries, 0 to 139
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   statusId  140 non-null    int64
 1   status    140 non-null    object
dtypes: int64(1), object(1)
memory usage: 2.3+ KB
None

Missing values
statusId    0
status      0
dtype: int64

Duplicate rows: 0

First rows

   statusId        status
0         1      Finished
1         2  Disqualified
2         3      Accident
3         4     Collision
4         5        Engine

In [26]:
for name in dfs:
    dfs[name] = dfs[name].replace(r"\N", np.nan)

In [27]:
def to_ms(value):
    if pd.isna(value):
        return pd.NA

    v = str(value).strip()

    # \N or empty
    if v in {"\\N", ""}:
        return pd.NA

    # +1 Lap / +2 Laps → not numeric
    if "Lap" in v:
        return pd.NA

    # +5.291s
    m = re.fullmatch(r"\+([\d.]+)s", v)
    if m:
        return int(float(m.group(1)) * 1000)

    # mm:ss.SSS or mm:ss.SS or mm:ss
    m = re.fullmatch(r"(\d+):(\d{1,2})(?:\.(\d+))?", v)
    if m:
        minutes = int(m.group(1))
        seconds = int(m.group(2))
        frac = m.group(3)

        ms = int(frac.ljust(3, "0")[:3]) if frac else 0
        return (minutes * 60 + seconds) * 1000 + ms

    return pd.NA

In [28]:
TIME_COLUMNS = {
    "lap_times": ["time"],
    "pit_stops": ["duration"],
    "qualifying": ["q1", "q2", "q3"],
    "results": ["time"]
}

for name, df in dfs.items():
    if name in TIME_COLUMNS:
        for col in TIME_COLUMNS[name]:
            if col in df.columns:
                df[col] = df[col].apply(to_ms).astype("Int64")

In [29]:
dfs["races"]["time"] = pd.to_datetime(
    dfs["races"]["time"],
    format="%H:%M:%S",
    errors="coerce"
).dt.time

In [30]:
for name, df in dfs.items():
    print("\n", name)
    print(df.dtypes[df.dtypes == "object"])

 circuits
circuitRef    object
name          object
location      object
country       object
url           object
dtype: object

 constructors
constructorRef    object
name              object
nationality       object
url               object
dtype: object

 constructor_results
status    object
dtype: object

 constructor_standings
position        object
positionText    object
dtype: object

 drivers
driverRef      object
number         object
code           object
forename       object
surname        object
dob            object
nationality    object
url            object
dtype: object

 driver_standings
position        object
positionText    object
dtype: object

 lap_times
Series([], dtype: object)

 pit_stops
time            object
milliseconds    object
dtype: object

 qualifying
Series([], dtype: object)

 races
name           object
date           object
time           object
url            object
fp1_date       object
fp1_time       object
fp2_date       object
fp2_time       object
fp3_date       object
fp3_time       object
quali_date     object
quali_time     object
sprint_date    object
sprint_time    object
dtype: object

 results
number             object
grid               object
position           object
positionText       object
milliseconds       object
fastestLap         object
rank               object
fastestLapTime     object
fastestLapSpeed    object
dtype: object

 seasons
url    object
dtype: object

 sprint_results
position          object
positionText      object
time              object
milliseconds      object
fastestLap        object
fastestLapTime    object
statusId          object
rank              object
dtype: object

 status
status    object
dtype: object

In [31]:
def parse_gap(value):
    if pd.isna(value):
        return pd.Series([pd.NA, pd.NA, pd.NA])

    v = str(value).strip()

    # +5.291s → time gap
    m = re.fullmatch(r"\+([\d.]+)s", v)
    if m:
        return pd.Series([int(float(m.group(1)) * 1000), pd.NA, "time"])

    # +1 Lap / +2 Laps → lap gap
    m = re.fullmatch(r"\+(\d+)\s*Laps?", v)
    if m:
        return pd.Series([pd.NA, int(m.group(1)), "lap"])

    # DNF / DNS / DSQ etc
    return pd.Series([pd.NA, pd.NA, v])

In [32]:
dfs["results"][["gap_ms", "gap_laps", "gap_type"]] = dfs["results"]["time"].apply(parse_gap)

In [33]:
for name, df in dfs.items():
    print("=" * 70)
    print(name.upper())
    print("=" * 70)

    print(df.info())

    print("\nMissing values")
    print(df.isna().sum())

    print("\nDuplicate rows:", df.duplicated().sum())

    print("\nFirst rows")
    display(df.head())

======================================================================
CIRCUITS
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   circuitId   78 non-null     int64
 1   circuitRef  78 non-null     object
 2   name        78 non-null     object
 3   location    78 non-null     object
 4   country     78 non-null     object
 5   lat         78 non-null     float64
 6   lng         78 non-null     float64
 7   alt         78 non-null     int64
 8   url         78 non-null     object
dtypes: float64(2), int64(2), object(5)
memory usage: 5.6+ KB
None

Missing values
circuitId     0
circuitRef    0
name          0
location      0
country       0
lat           0
lng           0
alt           0
url           0
dtype: int64

Duplicate rows: 0

First rows

,circuitId,circuitRef,name,location,country,lat,lng,alt,url
0,1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.84970,144.96800,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
1,2,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.73800,18,http://en.wikipedia.org/wiki/Sepang_Internatio...
2,3,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.03250,50.51060,7,http://en.wikipedia.org/wiki/Bahrain_Internati...
3,4,catalunya,Circuit de Barcelona-Catalunya,Montmeló,Spain,41.57000,2.26111,109,http://en.wikipedia.org/wiki/Circuit_de_Barcel...
4,5,istanbul,Istanbul Park,Istanbul,Turkey,40.95170,29.40500,130,http://en.wikipedia.org/wiki/Istanbul_Park

======================================================================
CONSTRUCTORS
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   constructorId   214 non-null    int64
 1   constructorRef  214 non-null    object
 2   name            214 non-null    object
 3   nationality     214 non-null    object
 4   url             214 non-null    object
dtypes: int64(1), object(4)
memory usage: 8.5+ KB
None

Missing values
constructorId     0
constructorRef    0
name              0
nationality       0
url               0
dtype: int64

Duplicate rows: 0

First rows

,constructorId,constructorRef,name,nationality,url
0,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
1,2,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso

======================================================================
CONSTRUCTOR_RESULTS
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12953 entries, 0 to 12952
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   constructorResultsId  12953 non-null  int64
 1   raceId                12953 non-null  int64
 2   constructorId         12953 non-null  int64
 3   points                12953 non-null  float64
 4   status                17 non-null     object
dtypes: float64(1), int64(3), object(1)
memory usage: 506.1+ KB
None

Missing values
constructorResultsId        0
raceId                      0
constructorId               0
points                      0
status                  12936
dtype: int64

Duplicate rows: 0

First rows

   constructorResultsId  raceId  constructorId  points status
0                     1      18              1    14.0    NaN
1                     2      18              2     8.0    NaN
2                     3      18              3     9.0    NaN
3                     4      18              4     5.0    NaN
4                     5      18              5     2.0    NaN

======================================================================
CONSTRUCTOR_STANDINGS
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13719 entries, 0 to 13718
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   constructorStandingsId  13719 non-null  int64
 1   raceId                  13719 non-null  int64
 2   constructorId           13719 non-null  int64
 3   points                  13719 non-null  float64
 4   position                13718 non-null  object
 5   positionText            13719 non-null  object
 6   wins                    13719 non-null  int64
dtypes: float64(1), int64(4), object(2)
memory usage: 750.4+ KB
None

Missing values
constructorStandingsId    0
raceId                    0
constructorId             0
points                    0
position                  1
positionText              0
wins                      0
dtype: int64

Duplicate rows: 0

First rows

,constructorStandingsId,raceId,constructorId,points,position,positionText,wins
0,1,18,1,14.0,1,1,1
1,2,18,2,8.0,3,3,0
2,3,18,3,9.0,2,2,0
3,4,18,4,5.0,4,4,0
4,5,18,5,2.0,5,5,0

======================================================================
DRIVERS
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 865 entries, 0 to 864
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   driverId     865 non-null    int64
 1   driverRef    865 non-null    object
 2   number       63 non-null     object
 3   code         108 non-null    object
 4   forename     865 non-null    object
 5   surname      865 non-null    object
 6   dob          865 non-null    object
 7   nationality  865 non-null    object
 8   url          865 non-null    object
dtypes: int64(1), object(8)
memory usage: 60.9+ KB
None

Missing values
driverId         0
driverRef        0
number         802
code           757
forename         0
surname          0
dob              0
nationality      0
url              0
dtype: int64

Duplicate rows: 0

First rows

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,NaN,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,NaN,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen

======================================================================
DRIVER_STANDINGS
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35537 entries, 0 to 35536
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   driverStandingsId  35537 non-null  int64
 1   raceId             35537 non-null  int64
 2   driverId           35537 non-null  int64
 3   points             35537 non-null  float64
 4   position           35524 non-null  object
 5   positionText       35537 non-null  object
 6   wins               35537 non-null  int64
dtypes: float64(1), int64(4), object(2)
memory usage: 1.9+ MB
None

Missing values
driverStandingsId     0
raceId                0
driverId              0
points                0
position             13
positionText          0
wins                  0
dtype: int64

Duplicate rows: 0

First rows

   driverStandingsId  raceId  driverId  points position positionText  wins
0                  1      18         1    10.0        1            1     1
1                  2      18         2     8.0        2            2     0
2                  3      18         3     6.0        3            3     0
3                  4      18         4     5.0        4            4     0
4                  5      18         5     4.0        5            5     0

======================================================================
LAP_TIMES
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 875093 entries, 0 to 875092
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   raceId        875093 non-null  int64
 1   driverId      875093 non-null  int64
 2   lap           875093 non-null  int64
 3   position      875093 non-null  int64
 4   time          875049 non-null  Int64
 5   milliseconds  875093 non-null  int64
dtypes: Int64(1), int64(5)
memory usage: 40.9 MB
None

Missing values
raceId           0
driverId         0
lap              0
position         0
time            44
milliseconds     0
dtype: int64

Duplicate rows: 1707

First rows

   raceId  driverId  lap  position    time  milliseconds
0     479       137    1         1  102085        102085
1     479       137    2         2   96287         96287
2     479       137    3         2   94627         94627
3     479       137    4         2   94041         94041
4     479       137    5         2   93699         93699

======================================================================
PIT_STOPS
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22424 entries, 0 to 22423
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   raceId        22424 non-null  int64
 1   driverId      22424 non-null  int64
 2   stop          22424 non-null  int64
 3   lap           22424 non-null  int64
 4   time          22424 non-null  object
 5   duration      764 non-null    Int64
 6   milliseconds  22421 non-null  object
dtypes: Int64(1), int64(4), object(2)
memory usage: 1.2+ MB
None

Missing values
raceId              0
driverId            0
stop                0
lap                 0
time                0
duration        21660
milliseconds        3
dtype: int64

Duplicate rows: 0

First rows

   raceId  driverId  stop  lap      time  duration milliseconds
0     258       100     1    1  14:01:34      <NA>        49111
1     258        79     1   17  14:20:46      <NA>        28482
2     258        57     1   18  14:22:35      <NA>        43745
3     258        71     1   18  14:23:00      <NA>        21992
4     258       105     1   19  14:24:39      <NA>        27693

======================================================================
QUALIFYING
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11146 entries, 0 to 11145
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   qualifyId      11146 non-null  int64
 1   raceId         11146 non-null  int64
 2   driverId       11146 non-null  int64
 3   constructorId  11146 non-null  int64
 4   number         11146 non-null  int64
 5   position       11146 non-null  int64
 6   q1             10982 non-null  Int64
 7   q2             6328 non-null   Int64
 8   q3             3942 non-null   Int64
dtypes: Int64(3), int64(6)
memory usage: 816.5 KB
None

Missing values
qualifyId           0
raceId              0
driverId            0
constructorId       0
number              0
position            0
q1                164
q2               4818
q3               7204
dtype: int64

Duplicate rows: 0

First rows

,qualifyId,raceId,driverId,constructorId,number,position,q1,q2,q3
0,1,18,1,1,22,1,86572,85187,86714
1,2,18,9,2,4,2,86103,85315,86869
2,3,18,5,1,23,3,85664,85452,87079
3,4,18,13,6,2,4,85994,85691,87178
4,5,18,2,2,3,5,85960,85518,87236

======================================================================
RACES
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1171 entries, 0 to 1170
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   raceId       1171 non-null   int64
 1   year         1171 non-null   int64
 2   round        1171 non-null   int64
 3   circuitId    1171 non-null   int64
 4   name         1171 non-null   object
 5   date         1171 non-null   object
 6   time         440 non-null    object
 7   url          1171 non-null   object
 8   fp1_date     136 non-null    object
 9   fp1_time     114 non-null    object
 10  fp2_date     118 non-null    object
 11  fp2_time     96 non-null     object
 12  fp3_date     106 non-null    object
 13  fp3_time     87 non-null     object
 14  quali_date   136 non-null    object
 15  quali_time   114 non-null    object
 16  sprint_date  30 non-null     object
 17  sprint_time  27 non-null     object
dtypes: int64(4), object(14)
memory usage: 164.8+ KB
None

Missing values
raceId            0
year              0
round             0
circuitId         0
name              0
date              0
time            731
url               0
fp1_date       1035
fp1_time       1057
fp2_date       1053
fp2_time       1075
fp3_date       1065
fp3_time       1084
quali_date     1035
quali_time     1057
sprint_date    1141
sprint_time    1144
dtype: int64

Duplicate rows: 0

First rows

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

======================================================================
RESULTS
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27414 entries, 0 to 27413
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   resultId         27414 non-null  int64
 1   raceId           27414 non-null  int64
 2   driverId         27414 non-null  int64
 3   constructorId    27414 non-null  int64
 4   number           27408 non-null  object
 5   grid             27394 non-null  object
 6   position         16461 non-null  object
 7   positionText     27414 non-null  object
 8   positionOrder    27414 non-null  int64
 9   points           27414 non-null  float64
 10  laps             27414 non-null  int64
 11  time             4 non-null      Int64
 12  milliseconds     8094 non-null   object
 13  fastestLap       8876 non-null   object
 14  rank             9134 non-null   object
 15  fastestLapTime   8876 non-null   object
 16  fastestLapSpeed  8252 non-null   object
 17  statusId         27414 non-null  int64
 18  gap_ms           0 non-null      object
 19  gap_laps         0 non-null      object
 20  gap_type         4 non-null      object
dtypes: Int64(1), float64(1), int64(7), object(12)
memory usage: 4.4+ MB
None

Missing values
resultId               0
raceId                 0
driverId               0
constructorId          0
number                 6
grid                  20
position           10953
positionText           0
positionOrder          0
points                 0
laps                   0
time               27410
milliseconds       19320
fastestLap         18538
rank               18280
fastestLapTime     18538
fastestLapSpeed    19162
statusId               0
gap_ms             27414
gap_laps           27414
gap_type           27410
dtype: int64

Duplicate rows: 0

First rows

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,...,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId,gap_ms,gap_laps,gap_type
0,1,18,1,1,22,1,1,1,1,10.0,...,<NA>,5690616,39,2,1:27.452,218.3,1,<NA>,<NA>,<NA>
1,2,18,2,2,3,5,2,2,2,8.0,...,<NA>,5696094,41,3,1:27.739,217.586,1,<NA>,<NA>,<NA>
2,3,18,3,3,7,7,3,3,3,6.0,...,<NA>,5698779,41,5,1:28.090,216.719,1,<NA>,<NA>,<NA>
3,4,18,4,4,5,11,4,4,4,5.0,...,<NA>,5707797,58,7,1:28.603,215.464,1,<NA>,<NA>,<NA>
4,5,18,5,1,23,3,5,5,5,4.0,...,<NA>,5708630,43,1,1:27.418,218.385,1,<NA>,<NA>,<NA>

======================================================================
SEASONS
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   year    77 non-null     int64
 1   url     77 non-null     object
dtypes: int64(1), object(1)
memory usage: 1.3+ KB
None

Missing values
year    0
url     0
dtype: int64

Duplicate rows: 0

First rows

   year                                                url
0  2009  http://en.wikipedia.org/wiki/2009_Formula_One_...
1  2008  http://en.wikipedia.org/wiki/2008_Formula_One_...
2  2007  http://en.wikipedia.org/wiki/2007_Formula_One_...
3  2006  http://en.wikipedia.org/wiki/2006_Formula_One_...
4  2005  http://en.wikipedia.org/wiki/2005_Formula_One_...

======================================================================
SPRINT_RESULTS
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 546 entries, 0 to 545
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   resultId        546 non-null    int64
 1   raceId          546 non-null    int64
 2   driverId        546 non-null    int64
 3   constructorId   546 non-null    int64
 4   number          546 non-null    int64
 5   grid            546 non-null    int64
 6   position        531 non-null    object
 7   positionText    546 non-null    object
 8   positionOrder   546 non-null    int64
 9   points          546 non-null    int64
 10  laps            546 non-null    int64
 11  time            508 non-null    object
 12  milliseconds    508 non-null    object
 13  fastestLap      530 non-null    object
 14  fastestLapTime  530 non-null    object
 15  statusId        544 non-null    object
 16  rank            179 non-null    object
dtypes: int64(9), object(8)
memory usage: 72.6+ KB
None

Missing values
resultId            0
raceId              0
driverId            0
constructorId       0
number              0
grid                0
position           15
positionText        0
positionOrder       0
points              0
laps                0
time               38
milliseconds       38
fastestLap         16
fastestLapTime     16
statusId            2
rank              367
dtype: int64

Duplicate rows: 0

First rows

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,fastestLapTime,statusId,rank
0,1,1061,830,9,33,2,1,1,1,3,17,25:38.426,1538426,14,1:30.013,1,NaN
1,2,1061,1,131,44,1,2,2,2,2,17,+1.430,1539856,17,1:29.937,1,NaN
2,3,1061,822,131,77,3,3,3,3,1,17,+7.502,1545928,17,1:29.958,1,NaN
3,4,1061,844,6,16,4,4,4,4,0,17,+11.278,1549704,16,1:30.163,1,NaN
4,5,1061,846,1,4,6,5,5,5,0,17,+24.111,1562537,16,1:30.566,1,NaN

======================================================================
STATUS
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140 entries, 0 to 139
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   statusId  140 non-null    int64
 1   status    140 non-null    object
dtypes: int64(1), object(1)
memory usage: 2.3+ KB
None

Missing values
statusId    0
status      0
dtype: int64

Duplicate rows: 0

First rows

   statusId        status
0         1      Finished
1         2  Disqualified
2         3      Accident
3         4     Collision
4         5        Engine

In [34]:
OUTPUT = Path("../data/processed/clean_parquet")
OUTPUT.mkdir(parents=True, exist_ok=True)

for name, df in dfs.items():
    df.to_parquet(
        OUTPUT / f"{name}.parquet",
        index=False
    )